name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: wget https://raw.githubusercontent.com/Tors-0/Classwork/master/src/CoolJavaGames.java
      - run: javac CoolJavaGames.java
      - run: jar -cf JavaGames.jar CoolJavaGames.class
